### ISSUE TITLE
win32console 1.3.1 doesn't work with redirected output

### ISSUE THREAD

**Issue by os97673** [luislavena/win32console#14] opened 2012-04-25 09:23 UTC
The test case is very simple:
$ cat win32console_test.rb
require 'win32console'

and "ruby win32console_test.rb" works fine, but "ruby win32console_test.rb | less" throws exception:
c:/Ruby192/lib/ruby/gems/1.9.1/gems/win32console-1.3.1-x86-mingw32/lib/Win32/Con
 (RuntimeError)`GetConsoleScreenBufferInfo': ═хтхЁэ√щ фхёъЁшяЄюЁ.
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/win32console-1.3.1-x86-mingw32/lib/Win32/Console.rb:210:in`Attr'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/win32console-1.3.1-x86-mingw32/lib/Win32/Console.rb:35:in `initialize'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/win32console-1.3.1-x86-mingw32/lib/Win32/Console/ANSI.rb:88:in`new'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/win32console-1.3.1-x86-mingw32/lib/Win32/Console/ANSI.rb:88:in `initialize'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/win32console-1.3.1-x86-mingw32/lib/Win32/Console/ANSI.rb:348:in`new'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/win32console-1.3.1-x86-mingw32/lib/Win32/Console/ANSI.rb:348:in `<top (required)>'
        from c:/Ruby192/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
        from c:/Ruby192/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/win32console-1.3.1-x86-mingw32/lib/win32console.rb:1:in`<top (required)>'
        from internal:lib/rubygems/custom_require:33:in `require'
        from <internal:lib/rubygems/custom_require>:33:in`rescue in require'
        from internal:lib/rubygems/custom_require:29:in `require'
        from win32console_test.rb:1:in`<main>'

It looks like GetConsoleScreenBufferInfo() should not be called for non-console streams.
In the code I see the check which doesn't call this method if the stream is not stderr or stdout but this is
not enough to detect if the function will work for it :(

**Comment by denofevil** [comment] 2012-04-25 19:19
Probably related to this commit: 57b7c6f8ee4b7171715255f633274bd2ffb1dfc5

**Comment by kbarber** [comment] 2012-05-09 22:14
I'm happy to look into this if you want @luislavena, since I broke it. Just assign it to me.

**Comment by luislavena** [comment] 2012-05-09 22:17
@kbarber I just used by magic wand and made you collaborator of the repository :smile:

Let's figure out how to solve that issue for redirected FD and do another release.

Thank you! :heart:

**Comment by kbarber** [comment] 2012-05-10 11:11
So the solution is in `Win32::Console::ANSI::IO#redirected?` - if the console is redirected the `@handle` variable becomes invalid everywhere and calls to `GetConsoleScreenBufferInfo` fail. Let me see how I can refactor so this `#redirected?` methodology is utilised with the new code introduced in 1.3.1.

**Comment by os97673** [comment] 2012-05-10 11:48
@kbarber 
Perhaps it would be more robust to wrap call Attr in begin...rescue instead.  This way you will be able to call the method for all streams which support this call and ignore all possible problems (just log the exception to inform developer)

What do you think?

**Comment by kbarber** [comment] 2012-05-10 12:29
@os97673 I can see the benefit in wrapping in begin rescue. Its obviously a heavier approach, but like you say might be more robust. I think we should limit it just to 'RuntimeError' in that case if we go that route.

Logging an exception in this case isn't necessarily possible - as piping to stuff isn't a problem per se, so we'll probably have to be silent.

... meditate on this proposal, I will.

**Comment by kbarber** [comment] 2012-05-10 15:02
I have a fix now in pull request 16. I ended up going down the 'redirected?' route instead of the exception handling, I'm still not sure if this is the right decision - but I feel that handling redirected? is going to help us in the future anyway. Happy to debate this solution of course.

I'm going to get someone from my team to test this on our CI machine for the failures we have been seeing. If anyone else can confirm this fix, it would be appreciated.

**Comment by luislavena** [comment] 2012-05-10 17:11
@os97673 @denofevil can you guys test against latest master again? I've merged changes from @kbarber.

Thank you

**Comment by os97673** [comment] 2012-05-11 10:24
@luislavena We've tested the new version and it works fine for us.

**Comment by kbarber** [comment] 2012-05-11 10:41
@luislavena my QA guys have confirmed that the failure we were seeing in our acceptance tests for Puppet have gone as well.

Thanks @os97673 for the confirmation. I'm going to close this bug.

**Closed as completed by kbarber** 2012-05-11 10:41 UTC
Labels: bug

**Comment by os97673** [comment] 2012-05-11 11:25
@kbarber @luislavena thank you for fixing the problem

**Comment by luislavena** [comment] 2012-05-11 13:22
@kbarber will wrap things for a release then.

Thank you @kbarber and @os97673 for testing things out.
