### ISSUE TITLE
Doesn't work with Ruby 19

### ISSUE THREAD

**Issue by hoornet** [luislavena/win32console#2] opened 2009-11-27 17:24 UTC
When I require it in my winXP I get this:
irb(main):002:0> require 'win32/console/ansi'
SyntaxError: C:/Ruby19/lib/ruby/gems/1.9.1/gems/win32console-1.2.0-x86-mingw32/l
ib/win32/console/ANSI.rb:325: invalid multibyte char (US-ASCII)
C:/Ruby19/lib/ruby/gems/1.9.1/gems/win32console-1.2.0-x86-mingw32/lib/win32/cons
ole/ANSI.rb:325: invalid multibyte char (US-ASCII)
C:/Ruby19/lib/ruby/gems/1.9.1/gems/win32console-1.2.0-x86-mingw32/lib/win32/cons
ole/ANSI.rb:325: syntax error, unexpected $end, expecting ')'
s.tr!("ÇüéâäůćçłëŐőŹÄĆÉĹĺôöĽľŚśÖÜŤŁ×čü...
^
from (irb):2:in `require'
from (irb):2
from C:/Ruby19/bin/irb:12:in`<main>'

http://isitruby19.com/win32console

**Comment by luislavena** [comment] 2009-11-27 17:29
Is a known issue, and is a duplicate of GH-1

**Closed as completed by luislavena** 2009-11-27 17:29 UTC
