### ISSUE TITLE
Does the console swallow "a" chars in mingw?

### ISSUE THREAD

**Issue by pke** [luislavena/win32console#5] opened 2010-03-03 10:17 UTC
I get weird output in mingw32:

Feture: Mnge trcks
  In order to mnge trcks
  s  user
  I wnt to crete nd mnge trcks

  Scenrio: Trcks List                               # fetures\mnge_trcks.feture:6
    Given I hve trcks titled Mm, We will rock you # fetures/step_definitions/trck_steps.rb:1
    When I go to the list of trcks                   # fetures\mnge_trcks.feture:8
      mbiguous mtch of "I go to the list of trcks":

```
  fetures/step_definitions/trck_steps.rb:7:in `/^I go to (.+)$/'
  fetures/step_definitions/web_steps.rb:18:in `/^(?:|I )go to (.+)$/'

  You cn run gin with --guess to mke Cucumber be more smrt bout it
   (Cucumber::mbiguous)
  fetures\mnge_trcks.feture:8:in `When I go to the list of trcks'
Then I should see "Mm"                          # fetures/step_definitions/web_steps.rb:142
nd I should see "We will rock you"               # fetures/step_definitions/web_steps.rb:142
```

Filing Scenrios:
cucumber fetures\mnge_trcks.feture:6 # Scenrio: Trcks List

1 scenrio (1 filed)
4 steps (1 filed, 2 skipped, 1 pssed)
0m0.511s

**Comment by luislavena** [comment] 2010-03-03 10:36
This has been already reported in Cucumber, please use the correct codepage and also use the pre-release version to see if the issue is fixed for you:

http://wiki.github.com/aslakhellesoy/cucumber/troubleshooting

http://blog.mmediasys.com/2009/12/29/win32console-1-3-0-prerelease/

Closing this as is a duplicate of an already resolved and worked out issue.

**Closed as completed by luislavena** 2010-03-03 10:36 UTC

**Comment by pke** [comment] 2010-03-03 12:16
Thanks for the swift response! The pre-release console fixed the issue. All other settings for cucumber where already correct here. Thanks!

**Comment by luislavena** [comment] 2010-03-03 12:19
You're welcome.

A known issue is autospec with win32console, still figuring it out why it doesn't work.

Cheers!
